-- Fiscal folios are globally sequenced per legal entity and series.
-- Deployment contract: apply migrations before starting or enabling issuer
-- backend instances. These locks also prevent old emitters from reserving a
-- type-scoped folio while the counters are consolidated.
BEGIN;

LOCK TABLE "FiscalFolioSequence" IN ACCESS EXCLUSIVE MODE;
LOCK TABLE "Invoice" IN SHARE ROW EXCLUSIVE MODE;

-- Read-only preflight under the migration lock. Non-numeric legacy folios are
-- reported but cannot collide with the numeric folios generated by this
-- sequence. Numeric values outside the usable BIGINT range fail closed.
DO $$
DECLARE
  non_numeric_folio_count BIGINT;
BEGIN
  SELECT COUNT(*)
    INTO non_numeric_folio_count
  FROM "Invoice"
  WHERE folio !~ '^[0-9]+$';

  RAISE NOTICE 'GLOBAL_FISCAL_FOLIO_SEQUENCE_NON_NUMERIC_FOLIOS=%',
    non_numeric_folio_count;

  IF EXISTS (
    SELECT 1
    FROM "Invoice"
    WHERE CASE
      WHEN folio ~ '^[0-9]+$'
        THEN folio::numeric > 9223372036854775806
      ELSE FALSE
    END
  ) THEN
    RAISE EXCEPTION 'GLOBAL_FISCAL_FOLIO_SEQUENCE_NUMERIC_FOLIO_OUT_OF_RANGE'
      USING ERRCODE = '22003';
  END IF;
END $$;

CREATE TEMPORARY TABLE "_FiscalFolioSequenceConsolidated" ON COMMIT DROP AS
WITH invoice_rollup AS (
  SELECT
    "legalEntityId",
    series,
    MAX(
      CASE
        WHEN folio ~ '^[0-9]+$' THEN folio::numeric
        ELSE NULL
      END
    ) AS "maxInvoiceNumericFolio"
  FROM "Invoice"
  GROUP BY "legalEntityId", series
),
sequence_rollup AS (
  SELECT
    "legalEntityId",
    series,
    MIN(id) AS id,
    MIN("createdAt") AS "createdAt",
    MAX("nextValue") AS "maxExistingSequenceNextValue"
  FROM "FiscalFolioSequence"
  GROUP BY "legalEntityId", series
),
sequence_keys AS (
  SELECT "legalEntityId", series FROM invoice_rollup
  UNION
  SELECT "legalEntityId", series FROM sequence_rollup
)
SELECT
  COALESCE(
    sequence_rollup.id,
    'global-fiscal-folio-' || md5(
      sequence_keys."legalEntityId"
      || ':' || length(sequence_keys.series)::text
      || ':' || sequence_keys.series
    )
  ) AS id,
  sequence_keys."legalEntityId",
  sequence_keys.series,
  GREATEST(
    COALESCE(invoice_rollup."maxInvoiceNumericFolio" + 1, 1),
    COALESCE(sequence_rollup."maxExistingSequenceNextValue", 1)
  ) AS "nextValue",
  COALESCE(sequence_rollup."createdAt", CURRENT_TIMESTAMP) AS "createdAt",
  CURRENT_TIMESTAMP AS "updatedAt"
FROM sequence_keys
LEFT JOIN invoice_rollup USING ("legalEntityId", series)
LEFT JOIN sequence_rollup USING ("legalEntityId", series);

DELETE FROM "FiscalFolioSequence";

INSERT INTO "FiscalFolioSequence" (
  id,
  "legalEntityId",
  "cfdiType",
  series,
  "nextValue",
  "createdAt",
  "updatedAt"
)
SELECT
  id,
  "legalEntityId",
  'INCOME'::"CfdiDocumentType",
  series,
  "nextValue"::BIGINT,
  "createdAt",
  "updatedAt"
FROM "_FiscalFolioSequenceConsolidated";

DROP INDEX "FiscalFolioSequence_legalEntityId_cfdiType_series_key";
ALTER TABLE "FiscalFolioSequence" DROP COLUMN "cfdiType";
CREATE UNIQUE INDEX "FiscalFolioSequence_legalEntityId_series_key"
  ON "FiscalFolioSequence"("legalEntityId", series);

COMMIT;
