export { ProductListPage } from './pages/ProductListPage'
export { ProductFormModal } from './components/ProductFormModal'
export { InventoryAdjustmentModal } from './components/InventoryAdjustmentModal'
export { InventoryByLocationView } from './components/InventoryByLocationView'
export { InventoryTransferView } from './components/InventoryTransferView'
export { InventoryMovementsView } from './components/InventoryMovementsView'
export { LowStockBadge } from './components/LowStockBadge'
export { productService } from './services/productService'
export * from './hooks/useProducts'
