export type CfdiDomainErrorCode =
  | 'INVALID_STATE_TRANSITION'
  | 'BILLING_REQUEST_NOT_FOUND'
  | 'BILLING_REQUEST_NOT_APPROVED'
  | 'CFDI_ALREADY_EXISTS'
  | 'EMPTY_BILLING_REQUEST'
  | 'MISSING_FISCAL_PROFILE'
  | 'MISSING_PRODUCT_FISCAL_PROFILE'
  | 'INVALID_CFDI_USE'
  | 'INVALID_PAYMENT_CONFIGURATION'
  | 'TOTAL_MISMATCH'
  | 'OVER_INVOICED'
  | 'MIXED_CUSTOMERS'
  | 'MIXED_CURRENCIES'
  | 'MIXED_LEGAL_ENTITIES'
  | 'CFDI_SUBSTITUTION_INVALID'
  | 'SAT_CATALOG_NOT_CONFIGURED'
  | 'SAT_CATALOG_CODE_NOT_FOUND'
  | 'PAYMENT_NOT_APPLIED'
  | 'REP_PAYMENT_FORM_MISSING'
  | 'REP_ORIGINAL_INVOICE_NOT_STAMPED'
  | 'REP_ORIGINAL_INVOICE_NOT_PPD'
  | 'REP_PAYMENT_EXCEEDS_AVAILABLE'
  | 'REP_UNALLOCATED_PAYMENT_AMOUNT'
  | 'REP_DUPLICATE_APPLICATION'
  | 'REP_OUT_OF_ORDER_PAYMENT'
  | 'REP_CURRENCY_MISMATCH'
  | 'REP_TAX_SNAPSHOT_MISSING'
  | 'REP_TAX_SNAPSHOT_INVALID'
  | 'REP_UNKNOWN_APPLICATION'
  | 'REP_ALREADY_ISSUED'
  | 'CREDIT_ADJUSTMENT_NOT_APPROVED'
  | 'CREDIT_ADJUSTMENT_SOURCE_REFERENCE_REQUIRED'
  | 'CREDIT_NOTE_ORIGINAL_INVOICE_NOT_STAMPED'
  | 'CREDIT_NOTE_ORIGINAL_INVOICE_CANCELLED'
  | 'CREDIT_NOTE_MIXED_PARTIES'
  | 'CREDIT_NOTE_CONCEPT_NOT_FOUND'
  | 'CREDIT_NOTE_TAX_SNAPSHOT_MISSING'
  | 'CREDIT_NOTE_OVER_CREDITED'
  | 'CREDIT_NOTE_ALREADY_ISSUED';

export class CfdiDomainError extends Error {
  constructor(
    readonly code: CfdiDomainErrorCode,
    readonly details?: Readonly<Record<string, unknown>>,
  ) {
    super(code);
    this.name = 'CfdiDomainError';
  }
}
