import { useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { AlertTriangle, ChevronDown, ChevronUp, FileCheck2, Filter, LoaderCircle, RefreshCw, Search, X } from 'lucide-react'
import { AnimatePresence, motion, useReducedMotion } from 'motion/react'
import { Button, Card } from '@/components/ui'
import { ConfirmationDialog } from '@/components/shared/confirmation-dialog'
import { MiniAjaxSelect } from '@/components/shared/operational-catalogs'
import { formatMoney as money } from '@/lib/money'
import { useAuth } from '../auth'
import { useBillingReport, useBillingReportDetail, useBillingRequestCommand } from './hooks'
import { getDetailPropertyLabel } from './detailLabels'
import { areNotesCompatible, isRequestableNote } from './selection'
import type { BillingReportFilters, BillingReportItem, BillingStatus } from './types'

const field = 'h-11 rounded-xl border border-[color:var(--erp-border)] bg-white px-3 text-sm font-semibold outline-none focus:border-[var(--erp-brand-gold)] focus:ring-2 focus:ring-[rgba(214,155,45,.18)]'
const statusLabel: Record<BillingStatus, string> = { NOT_BILLABLE: 'No facturable', BILLABLE: 'Facturable', PENDING_INFORMATION: 'Información pendiente', REQUESTED: 'Solicitada', IN_PROCESS: 'En proceso', PARTIALLY_INVOICED: 'Facturada parcialmente', FULLY_INVOICED: 'Facturada', BLOCKED: 'Bloqueada', CANCELLED: 'Cancelada' }
const statusTone: Record<BillingStatus, string> = { NOT_BILLABLE: 'bg-slate-100 text-slate-700', BILLABLE: 'bg-emerald-100 text-emerald-800', PENDING_INFORMATION: 'bg-amber-100 text-amber-800', REQUESTED: 'bg-blue-100 text-blue-800', IN_PROCESS: 'bg-indigo-100 text-indigo-800', PARTIALLY_INVOICED: 'bg-violet-100 text-violet-800', FULLY_INVOICED: 'bg-emerald-100 text-emerald-800', BLOCKED: 'bg-red-100 text-red-800', CANCELLED: 'bg-slate-200 text-slate-700' }
const booleanFilter = (params: URLSearchParams, key: string) => params.has(key) ? params.get(key) === 'true' : undefined
function parseFilters(params: URLSearchParams): BillingReportFilters { return {
  page: Number(params.get('page') || 1), limit: Number(params.get('limit') || 25), search: params.get('search') || '',
  billingStatus: (params.get('billingStatus') || '') as BillingStatus | '', documentType: params.get('documentType') || '',
  dateFrom: params.get('dateFrom') || '', dateTo: params.get('dateTo') || '', locationId: params.get('locationId') || '',
  customerId: params.get('customerId') || '', taxId: params.get('taxId') || '', sellerId: params.get('sellerId') || '', routeId: params.get('routeId') || '',
  paymentStatus: params.get('paymentStatus') || '', deliveryStatus: params.get('deliveryStatus') || '', hasRequest: booleanFilter(params, 'hasRequest'),
  fiscalProfileComplete: booleanFilter(params, 'fiscalProfileComplete'), overdue: booleanFilter(params, 'overdue'), blocked: booleanFilter(params, 'blocked'),
  folio: params.get('folio') || '', uuid: params.get('uuid') || '', sortBy: params.get('sortBy') || 'issuedAt', sortOrder: (params.get('sortOrder') || 'desc') as 'asc' | 'desc',
} }

const triState = (value: boolean | undefined) => value === undefined ? '' : String(value)
const optionalBoolean = (value: string) => value === '' ? undefined : value === 'true'

export function BillingReportableNotesPage() {
  const { user } = useAuth()
  const shouldReduceMotion = useReducedMotion()
  const [params, setParams] = useSearchParams()
  const filters = useMemo(() => parseFilters(params), [params])
  const report = useBillingReport(filters)
  const [selected, setSelected] = useState<string[]>([])
  const [detailId, setDetailId] = useState<string>()
  const [dialog, setDialog] = useState<{ kind: 'create' } | { kind: 'review'; id: string; action: 'approve' | 'reject' | 'cancel'; version: number }>()
  const [reason, setReason] = useState('')
  const [selectedItems, setSelectedItems] = useState<Record<string, string[]>>({})
  const detail = useBillingReportDetail(detailId)
  const command = useBillingRequestCommand()
  const data = report.data
  const rowsById = new Map(data?.items.map((item) => [item.saleDocumentId, item]))
  const selectedRows = selected.map((id) => rowsById.get(id)).filter((item): item is BillingReportItem => Boolean(item))
  const canReview = user?.role === 'ADMIN' || user?.role === 'BILLING'
  const canCreate = user?.role === 'ADMIN' || user?.role === 'SELLER'
  const invalidRequestedAmount = dialog?.kind === 'create' && selectedRows.some((item) => !(selectedItems[item.saleDocumentId]?.length))
  const advancedKeys: Array<keyof BillingReportFilters> = ['dateFrom', 'dateTo', 'locationId', 'customerId', 'taxId', 'sellerId', 'routeId', 'paymentStatus', 'deliveryStatus', 'hasRequest', 'fiscalProfileComplete', 'overdue', 'blocked', 'folio', 'uuid']
  const advancedCount = advancedKeys.filter((key) => filters[key] !== undefined && filters[key] !== '').length

  function update(next: Partial<BillingReportFilters>) { const merged = { ...filters, ...next, page: next.page ?? 1 }; const nextParams = new URLSearchParams(); Object.entries(merged).forEach(([key, value]) => { if (value !== undefined && value !== '') nextParams.set(key, String(value)) }); setParams(nextParams) }
  function toggle(item: BillingReportItem) { setSelected((current) => current.includes(item.saleDocumentId) ? current.filter((id) => id !== item.saleDocumentId) : isRequestableNote(item) && (current.length === 0 || areNotesCompatible(rowsById.get(current[0])!, item)) ? [...current, item.saleDocumentId] : current) }
  function sort(sortBy: string) { update({ sortBy, sortOrder: filters.sortBy === sortBy && filters.sortOrder === 'asc' ? 'desc' : 'asc' }) }
  function clearAdvancedFilters() { update(Object.fromEntries(advancedKeys.map((key) => [key, undefined]))) }
  async function confirm() { if (!dialog || !reason.trim()) return; if (dialog.kind === 'create') { await command.mutateAsync({ kind: 'create', body: { customerId: selectedRows[0].customerId, reason: reason.trim(), documents: selectedRows.map((item) => { const items = item.requestableItems.filter((candidate) => selectedItems[item.saleDocumentId]?.includes(candidate.saleItemId)); const sum = (field: 'pendingSubtotal' | 'pendingTax' | 'pendingTotal') => items.reduce((total, candidate) => total + Number(candidate[field]), 0).toFixed(2); return { saleDocumentId: item.saleDocumentId, items: items.map((candidate) => ({ saleItemId: candidate.saleItemId })), requestedSubtotal: sum('pendingSubtotal'), requestedTax: sum('pendingTax'), requestedTotal: sum('pendingTotal') } }) } }); setSelected([]); setSelectedItems({}) } else await command.mutateAsync({ kind: 'review', id: dialog.id, action: dialog.action, expectedVersion: dialog.version, reason: reason.trim() }); setDialog(undefined); setReason('') }

  return <main className="min-h-screen bg-[var(--erp-background)] px-4 py-6 text-[var(--erp-foreground)] sm:px-6 lg:px-8"><div className="mx-auto grid max-w-[1500px] gap-5">
    <header className="relative overflow-hidden rounded-[1.75rem] bg-[var(--erp-charcoal)] p-6 text-white shadow-[var(--erp-shadow-elevated)] sm:p-8"><div className="absolute inset-y-0 right-0 w-2 bg-[var(--erp-brand-gold)]" /><p className="text-xs font-black uppercase tracking-[.22em] text-[var(--erp-brand-gold-soft)]">Conciliación documental</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-black tracking-[-.05em] sm:text-4xl">Notas facturables</h1><p className="mt-2 max-w-3xl text-sm text-white/70">Controla solicitudes y facturas externas sin emitir CFDI ni modificar ventas, pagos o inventario.</p></div>{report.isFetching && !report.isLoading && <span className="flex items-center gap-2 text-sm font-bold text-white/70"><RefreshCw className="h-4 w-4 animate-spin" />Actualizando</span>}</div></header>
    {data?.isStale && <div className="flex items-center gap-3 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm font-bold text-amber-900"><AlertTriangle className="h-5 w-5" />Los datos tienen {data.freshnessSeconds} segundos de antigüedad. Actualiza antes de decidir.</div>}
    <section aria-label="Indicadores" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{data && [[data.summary.billableDocuments, 'Notas listas'], [money(data.summary.totalRequested), 'Importe solicitado'], [money(data.summary.totalInvoiced), 'Importe facturado'], [money(data.summary.totalPending), 'Pendiente por facturar']].map(([value, label]) => <Card className="border-l-4 border-l-[var(--erp-brand-gold)] p-5" key={label}><p className="text-xs font-black uppercase tracking-[.15em] text-[var(--erp-muted-foreground)]">{label}</p><p className="mt-2 text-2xl font-black tracking-[-.04em]">{value}</p></Card>)}</section>
    <Card className="p-5"><div className="mb-4 flex items-center gap-2 font-black"><Filter className="h-5 w-5" />Filtros del reporte</div><div className="grid gap-3 md:grid-cols-4"><label className="relative md:col-span-2"><span className="sr-only">Buscar</span><Search className="absolute left-3 top-3.5 h-4 w-4 text-[var(--erp-muted-foreground)]" /><input className={`${field} w-full pl-9`} onChange={(event) => update({ search: event.target.value })} placeholder="Venta, cliente, folio o RFC" value={filters.search} /></label><select aria-label="Estado de facturación" className={field} onChange={(event) => update({ billingStatus: event.target.value as BillingStatus | '' })} value={filters.billingStatus}>{<option value="">Todos los estados</option>}{Object.entries(statusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="Tipo documental" className={field} onChange={(event) => update({ documentType: event.target.value })} value={filters.documentType}><option value="">Todos los documentos</option><option value="SIMPLE_NOTE">Nota simple</option><option value="LARGE_NOTE">Nota grande</option></select></div>
      <details className="mt-4 border-t border-[color:var(--erp-border)] pt-4" open={advancedCount > 0}><summary className="flex cursor-pointer list-none items-center justify-between rounded-xl px-1 py-2 font-black focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--erp-brand-gold)]"><span>Filtros avanzados{advancedCount > 0 && <span className="ml-2 rounded-full bg-[var(--erp-brand-gold-soft)] px-2 py-0.5 text-xs text-[var(--erp-charcoal)]">{advancedCount} activos</span>}</span><ChevronDown className="h-4 w-4" /></summary>
        <div className="mt-3 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <FilterField label="Fecha inicial"><input className={`${field} w-full`} onChange={(event) => update({ dateFrom: event.target.value })} type="date" value={filters.dateFrom} /></FilterField>
          <FilterField label="Fecha final"><input className={`${field} w-full`} onChange={(event) => update({ dateTo: event.target.value })} type="date" value={filters.dateTo} /></FilterField>
          <MiniAjaxSelect className={`${field} w-full`} endpoint="/locations?isActive=true" label="Ubicación" onChange={(locationId) => update({ locationId })} placeholder="Buscar ubicación" value={filters.locationId} />
          <MiniAjaxSelect className={`${field} w-full`} endpoint="/customers?isActive=true" label="Cliente" onChange={(customerId) => update({ customerId })} placeholder="Buscar cliente" value={filters.customerId} />
          <FilterField label="RFC"><input className={`${field} w-full font-mono`} onChange={(event) => update({ taxId: event.target.value.toUpperCase() })} placeholder="RFC completo o parcial" value={filters.taxId} /></FilterField>
          <MiniAjaxSelect className={`${field} w-full`} endpoint="/users?role=SELLER&status=active" label="Vendedor" onChange={(sellerId) => update({ sellerId })} placeholder="Buscar vendedor" value={filters.sellerId} />
          <MiniAjaxSelect className={`${field} w-full`} endpoint="/delivery-routes" label="Ruta" onChange={(routeId) => update({ routeId })} placeholder="Buscar ruta" value={filters.routeId} />
          <FilterSelect label="Estado de pago" onChange={(paymentStatus) => update({ paymentStatus })} options={[['PAID','Pagado'],['PARTIALLY_PAID','Pago parcial'],['UNPAID','Sin pago']]} value={filters.paymentStatus} />
          <FilterSelect label="Estado de entrega" onChange={(deliveryStatus) => update({ deliveryStatus })} options={[['PENDING','Pendiente'],['IN_ROUTE','En ruta'],['DELIVERED','Entregada'],['NOT_DELIVERED','No entregada'],['PARTIALLY_REJECTED','Rechazo parcial'],['RETURNED','Devuelta'],['CANCELLED','Cancelada']]} value={filters.deliveryStatus} />
          <FilterSelect label="Solicitud" onChange={(value) => update({ hasRequest: optionalBoolean(value) })} options={[['true','Con solicitud'],['false','Sin solicitud']]} value={triState(filters.hasRequest)} />
          <FilterSelect label="Perfil fiscal" onChange={(value) => update({ fiscalProfileComplete: optionalBoolean(value) })} options={[['true','Completo'],['false','Incompleto']]} value={triState(filters.fiscalProfileComplete)} />
          <FilterSelect label="Vencimiento" onChange={(value) => update({ overdue: optionalBoolean(value) })} options={[['true','Vencida'],['false','Vigente']]} value={triState(filters.overdue)} />
          <FilterSelect label="Bloqueo" onChange={(value) => update({ blocked: optionalBoolean(value) })} options={[['true','Bloqueada'],['false','Sin bloqueo']]} value={triState(filters.blocked)} />
          <FilterField label="Folio"><input className={`${field} w-full`} onChange={(event) => update({ folio: event.target.value })} placeholder="Folio visible" value={filters.folio} /></FilterField>
          <FilterField label="UUID"><input className={`${field} w-full font-mono`} onChange={(event) => update({ uuid: event.target.value })} placeholder="UUID de factura externa" value={filters.uuid} /></FilterField>
        </div>{advancedCount > 0 && <div className="mt-4 flex justify-end"><Button onClick={clearAdvancedFilters} variant="ghost">Limpiar filtros avanzados</Button></div>}
      </details>
    </Card>
      {selected.length > 0 && <div className="sticky top-3 z-20 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[rgba(214,155,45,.4)] bg-[#fffaf0] p-4 shadow-lg"><div><strong>{selected.length} notas compatibles</strong><p className="text-xs text-[var(--erp-muted-foreground)]">{money(selectedRows.reduce((sum, item) => sum + Number(item.pendingTotal), 0).toFixed(2))} disponible por solicitar</p></div><div className="flex gap-2"><Button onClick={() => setSelected([])} variant="outline">Limpiar</Button>{canCreate && <Button onClick={() => { setReason(''); setSelectedItems(Object.fromEntries(selectedRows.map((item) => [item.saleDocumentId, item.requestableItems.map((candidate) => candidate.saleItemId)]))); setDialog({ kind: 'create' }) }}>Crear solicitud agrupada</Button>}</div></div>}
    <Card className="overflow-hidden"><div className="border-b border-[color:var(--erp-border)] p-5"><h2 className="text-lg font-black">Bandeja documental</h2><p className="text-sm text-[var(--erp-muted-foreground)]">{data?.pagination.total ?? 0} notas bajo tu alcance</p></div>
      {report.isLoading && <div className="flex items-center justify-center gap-3 p-14"><LoaderCircle className="h-5 w-5 animate-spin" />Cargando notas…</div>}{report.error && <div className="p-10 text-center"><p className="font-black text-[var(--erp-danger)]">No se pudieron cargar las notas facturables.</p><Button className="mt-4" onClick={() => void report.refetch()} variant="outline">Reintentar</Button></div>}
      {!report.isLoading && !report.error && !data?.items.length && <div className="p-14 text-center"><FileCheck2 className="mx-auto h-10 w-10 text-[var(--erp-muted-foreground)]" /><p className="mt-3 font-black">No hay notas con estos filtros</p><p className="text-sm text-[var(--erp-muted-foreground)]">Ajusta los filtros sin perder el contexto de la bandeja.</p></div>}
      {!!data?.items.length && <div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-left text-sm"><thead className="bg-[var(--erp-surface)] text-xs uppercase tracking-[.12em] text-[var(--erp-muted-foreground)]"><tr><th className="p-4"><span className="sr-only">Seleccionar</span></th>{[['saleNumber','Venta'],['customerName','Cliente'],['billingStatus','Estado'],['total','Total'],['pendingInvoice','Pendiente']].map(([key,label]) => <th className="p-4" key={key}><button className="flex items-center gap-1 font-black" onClick={() => sort(key)}>{label}{filters.sortBy === key && (filters.sortOrder === 'asc' ? <ChevronUp className="h-3 w-3" /> : <ChevronDown className="h-3 w-3" />)}</button></th>)}<th className="p-4">Saldo documental</th><th className="p-4">Acción</th></tr></thead><tbody>{data.items.map((item) => { const anchor = selectedRows[0]; const selectable = canCreate && isRequestableNote(item) && (!anchor || areNotesCompatible(anchor, item)); const ratio = Math.min(100, Number(item.activeInvoiced) / Math.max(Number(item.total), 1) * 100); return <tr className="border-t border-[color:var(--erp-border)] hover:bg-[var(--erp-surface-muted)]" key={item.saleDocumentId}><td className="p-4"><input aria-label={`Seleccionar ${item.saleNumber}`} checked={selected.includes(item.saleDocumentId)} disabled={!selectable} onChange={() => toggle(item)} type="checkbox" /></td><td className="p-4"><strong>{item.saleNumber}</strong><p className="text-xs text-[var(--erp-muted-foreground)]">{item.physicalFolio || item.documentType}</p></td><td className="p-4"><strong>{item.customerName}</strong>{item.taxId && <p className="font-mono text-xs">{item.taxId}</p>}</td><td className="p-4"><span className={`rounded-full px-2.5 py-1 text-xs font-black ${statusTone[item.billingStatus]}`}>{statusLabel[item.billingStatus]}</span></td><td className="p-4 font-black">{money(item.total)}</td><td className="p-4 font-black text-[var(--erp-brand-red)]">{money(item.pendingInvoice)}</td><td className="p-4"><div className="h-2 w-36 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-[var(--erp-brand-gold)]" style={{ width: `${ratio}%` }} /></div><p className="mt-1 text-xs">{money(item.activeInvoiced)} facturado</p></td><td className="p-4"><Button onClick={() => setDetailId(item.saleDocumentId)} variant="outline">Ver detalle</Button></td></tr>})}</tbody></table></div>}
      <div className="flex items-center justify-between border-t border-[color:var(--erp-border)] p-4"><Button disabled={(filters.page ?? 1) <= 1} onClick={() => update({ page: (filters.page ?? 1) - 1 })} variant="outline">Anterior</Button><span className="text-sm font-bold">Página {data?.pagination.page ?? 1} de {Math.max(data?.pagination.totalPages ?? 1, 1)}</span><Button disabled={(filters.page ?? 1) >= (data?.pagination.totalPages ?? 1)} onClick={() => update({ page: (filters.page ?? 1) + 1 })} variant="outline">Siguiente</Button></div></Card>
  </div><AnimatePresence>{detailId && <motion.div animate={{ opacity: 1 }} className="fixed inset-0 z-40 bg-[rgba(17,24,21,0.42)] backdrop-blur-[2px]" exit={{ opacity: 0 }} initial={{ opacity: 0 }} transition={{ duration: shouldReduceMotion ? 0 : 0.2, ease: 'easeOut' }}><button aria-label="Cerrar capa del detalle" className="absolute inset-0 h-full w-full cursor-default" onClick={() => setDetailId(undefined)} type="button" /><motion.aside animate={{ x: 0 }} aria-label="Detalle de nota facturable" aria-modal="true" className="absolute inset-y-0 right-0 w-full max-w-xl overflow-y-auto border-l border-[color:var(--erp-border)] bg-white p-5 shadow-2xl" exit={{ x: '100%' }} initial={{ x: '100%' }} role="dialog" transition={{ duration: shouldReduceMotion ? 0 : 0.24, ease: 'easeOut' }}><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[var(--erp-brand-gold-deep)]">Expediente documental</p><h2 className="mt-1 text-2xl font-black">{detail.data?.saleNumber ?? 'Cargando detalle…'}</h2></div><Button aria-label="Cerrar detalle" onClick={() => setDetailId(undefined)} variant="ghost"><X /></Button></div>{detail.isLoading && <p className="mt-8">Cargando expediente…</p>}{detail.error && <p className="mt-8 font-bold text-[var(--erp-danger)]">No se pudo cargar el detalle.</p>}{detail.data && <div className="mt-6 grid gap-5"><section className="rounded-xl bg-[var(--erp-surface-muted)] p-4"><h3 className="font-black">Venta y cliente</h3><p>{detail.data.customerName} · {detail.data.locationName}</p>{user?.role !== 'COLLECTIONS' && detail.data.taxId && <p className="mt-1 font-mono text-sm">RFC {detail.data.taxId}</p>}</section><DetailSection title="Partidas" rows={detail.data.items} empty="Sin partidas" /><DetailSection title="Solicitudes" rows={detail.data.requests} empty="Sin solicitudes" />{canReview && detail.data.requests.filter((request) => ['REQUESTED','IN_REVIEW'].includes(request.status)).map((request) => <div className="flex gap-2" key={request.id}><Button onClick={() => setDialog({ kind: 'review', id: request.id, action: 'approve', version: request.version })}>Aprobar</Button><Button onClick={() => setDialog({ kind: 'review', id: request.id, action: 'reject', version: request.version })} variant="outline">Rechazar</Button></div>)}<DetailSection title="Facturas vigentes" rows={detail.data.activeInvoices} empty="Sin facturas vigentes" /><DetailSection title="Historial de facturas" rows={detail.data.invoiceHistory} empty="Sin facturas históricas" /><DetailSection title="Pagos" rows={detail.data.payments} empty="Sin pagos" /><DetailSection title="Entrega" rows={detail.data.delivery ? [detail.data.delivery] : []} empty="Sin entrega" /><DetailSection title="Auditoría" rows={detail.data.audit} empty="Sin eventos de auditoría" /></div>}</motion.aside></motion.div>}</AnimatePresence>
    <ConfirmationDialog confirmDisabled={!reason.trim() || Boolean(invalidRequestedAmount)} confirmLabel={dialog?.kind === 'create' ? 'Crear solicitud' : dialog?.action === 'approve' ? 'Aprobar solicitud' : 'Confirmar acción'} description="Esta operación quedará registrada con actor, motivo y fecha." isLoading={command.isPending} onConfirm={confirm} onOpenChange={(open) => { if (!open) setDialog(undefined) }} open={Boolean(dialog)} title={dialog?.kind === 'create' ? 'Confirmar solicitud agrupada' : 'Confirmar revisión'}>{dialog?.kind === 'create' && <div className="grid gap-3"><strong>Partidas por solicitar</strong>{selectedRows.map((item) => <fieldset className="rounded-xl border border-[color:var(--erp-border)] p-3" key={item.saleDocumentId}><legend className="px-1 text-xs font-black">{item.saleNumber}</legend>{item.requestableItems.map((candidate) => <label className="flex items-center justify-between gap-3 py-2 text-xs" key={candidate.saleItemId}><span className="flex items-center gap-2"><input checked={selectedItems[item.saleDocumentId]?.includes(candidate.saleItemId) ?? false} onChange={() => setSelectedItems((current) => ({ ...current, [item.saleDocumentId]: current[item.saleDocumentId]?.includes(candidate.saleItemId) ? current[item.saleDocumentId].filter((id) => id !== candidate.saleItemId) : [...(current[item.saleDocumentId] ?? []), candidate.saleItemId] }))} type="checkbox" />{candidate.productName}</span><span className="font-mono font-bold">{money(candidate.pendingTotal)}</span></label>)}</fieldset>)}</div>}<label className="grid gap-2 font-bold">Motivo obligatorio<textarea autoFocus className={`${field} min-h-24 py-3`} onChange={(event) => setReason(event.target.value)} value={reason} /></label>{command.error && <p className="text-[var(--erp-danger)]">{command.error.message}</p>}</ConfirmationDialog>
  </main>
}

function DetailSection({ title, rows, empty }: { title: string; rows: Array<Record<string, unknown>>; empty: string }) { return <section><h3 className="mb-2 font-black">{title}</h3>{rows.length ? <div className="grid gap-2">{rows.map((row, index) => <pre className="overflow-x-auto rounded-xl border border-[color:var(--erp-border)] bg-[var(--erp-surface-muted)] p-3 text-xs whitespace-pre-wrap" key={String(row.id ?? index)}>{Object.entries(row).filter(([,value]) => value !== null).map(([key,value]) => `${getDetailPropertyLabel(key)}: ${String(value)}`).join('\n')}</pre>)}</div> : <p className="text-sm text-[var(--erp-muted-foreground)]">{empty}</p>}</section> }

function FilterField({ children, label }: { children: React.ReactNode; label: string }) { return <label className="grid gap-1.5 text-xs font-black uppercase tracking-[.08em] text-[var(--erp-muted-foreground)]"><span>{label}</span>{children}</label> }
function FilterSelect({ label, onChange, options, value }: { label: string; onChange: (value: string) => void; options: Array<[string, string]>; value?: string }) { return <FilterField label={label}><select className={`${field} w-full normal-case tracking-normal text-[var(--erp-foreground)]`} onChange={(event) => onChange(event.target.value)} value={value ?? ''}><option value="">Todos</option>{options.map(([optionValue, optionLabel]) => <option key={optionValue} value={optionValue}>{optionLabel}</option>)}</select></FilterField> }
