-- Employee identity is generated by PostgreSQL so concurrent registrations never
-- share a control number.
CREATE SEQUENCE "User_controlNumber_seq" START WITH 1 INCREMENT BY 1;

ALTER TABLE "User"
  ADD COLUMN "controlNumber" TEXT,
  ADD COLUMN "phone" TEXT,
  ADD COLUMN "operationalLocationId" TEXT;

INSERT INTO "OperationalLocation" ("id", "name", "code", "type", "isActive", "createdAt", "updatedAt")
SELECT 'legacy-employees-location', 'Asignación pendiente', 'LEGACY-EMPLOYEES', 'MIXED', true, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM "OperationalLocation" WHERE "id" = 'legacy-employees-location');

UPDATE "User"
SET "controlNumber" = 'EPDP-' || LPAD(nextval('"User_controlNumber_seq"')::text, 6, '0'),
    "phone" = 'legacy-' || "id",
    "operationalLocationId" = 'legacy-employees-location'
WHERE "controlNumber" IS NULL;

ALTER TABLE "User"
  ALTER COLUMN "controlNumber" SET NOT NULL,
  ALTER COLUMN "phone" SET NOT NULL,
  ALTER COLUMN "operationalLocationId" SET NOT NULL;

ALTER TABLE "User" ADD CONSTRAINT "User_controlNumber_key" UNIQUE ("controlNumber");
ALTER TABLE "User" ADD CONSTRAINT "User_phone_key" UNIQUE ("phone");
CREATE INDEX "User_operationalLocationId_idx" ON "User"("operationalLocationId");
ALTER TABLE "User" ADD CONSTRAINT "User_operationalLocationId_fkey"
  FOREIGN KEY ("operationalLocationId") REFERENCES "OperationalLocation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
